### ISSUE TITLE
set PYTHONUTF8=1 to run on Windows

### ISSUE THREAD

**Issue by jrobbins-LiveData** [bneijt/poetry-lock-package#35]
In order to run `poetry-lock-package` on Windows, I had to first set this environment variable

```cmd
set PYTHONUTF8=1
```

This [article](https://dev.to/methane/python-use-utf-8-mode-on-windows-212i) explains the reason why.

Without setting it, this is the traceback I saw

```
Traceback (most recent call last):
  File "[redacted]\.pyenv\pyenv-win\versions\3.9.13\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "[redacted]\.pyenv\pyenv-win\versions\3.9.13\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "[redacted]\.venv\Scripts\poetry-lock-package.exe\__main__.py", line 7, in <module>
  File "[redacted]\.venv\lib\site-packages\poetry_lock_package\app.py", line 177, in main
    run(
  File "[redacted]\.venv\lib\site-packages\poetry_lock_package\app.py", line 205, in run
    lock = read_toml("poetry.lock")
  File "[redacted]\.venv\lib\site-packages\poetry_lock_package\util.py", line 35, in read_toml
    return toml.load(project_file)
  File "[redacted]\.venv\lib\site-packages\toml\decoder.py", line 156, in load
    return loads(f.read(), _dict, decoder)
  File "[redacted]\.pyenv\pyenv-win\versions\3.9.13\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 152586: character maps to <undefined>
```

**Comment by bneijt** [comment]
Almost a year after this issue was files, btw thank you for that, I'm revisiting this. I'm currently working at a company that only wants Windows machines so I think I might be able to test the above issue and see if I can reproduce and fix it. Hopefully other users have found your work-around in the meantime.
